-- Ques4

CREATE DATABASE temp;

use temp;

CREATE TABLE
    S(
        SNO CHAR(2) NOT NULL COMMENT '供应商代码' PRIMARY KEY,
        SNAME VARCHAR(5) NOT NULL COMMENT '供应商姓名',
        STATUS SMALLINT NOT NULL COMMENT '供应商状态',
        CITY VARCHAR(5) NOT NULL COMMENT '供应商所在城市'
    );

CREATE TABLE
    P(
        PNO CHAR(2) NOT NULL COMMENT '零件代码' PRIMARY KEY,
        PNAME VARCHAR(5) NOT NULL COMMENT '零件名',
        COLOR CHAR NOT NULL COMMENT '颜色',
        WEIGHT SMALLINT NOT NULL COMMENT '重量'
    );

CREATE TABLE
    J(
        JNO CHAR(2) NOT NULL COMMENT '工程项目代码' PRIMARY KEY,
        JNAME VARCHAR(5) NOT NULL COMMENT '工程项目名',
        CITY VARCHAR(5) NOT NULL COMMENT '工程项目所在城市'
    );

CREATE TABLE
    SPJ(
        SNO CHAR(2) NOT NULL COMMENT '供应商代码' NOT NULL,
        PNO CHAR(2) NOT NULL COMMENT '零件代码' NOT NULL,
        JNO CHAR(2) NOT NULL COMMENT '工程项目代码' NOT NULL,
        QTY SMALLINT NOT NULL COMMENT '供应数量' NOT NULL,
        PRIMARY KEY(SNO, PNO, JNO),
        FOREIGN KEY(SNO) REFERENCES S(SNO),
        FOREIGN KEY(PNO) REFERENCES P(PNO),
        FOREIGN KEY(JNO) REFERENCES J(JNO)
    );

-- Ques5

USE temp;

-- 1

SELECT SNAME,CITY FROM S;

-- 2

SELECT PNAME,COLOR,WEIGHT FROM P;

-- 3

SELECT JNO FROM SPJ WHERE SNO='S1';

-- 4

SELECT PNAME, QTY FROM P, SPJ WHERE P.PNO=SPJ.PNO AND SPJ.JNO='J2';

-- 5

SELECT PNO FROM SPJ WHERE SNO IN(SELECT SNO FRON S WHERE CITY='上海');

-- 6

SELECT JNAME
FROM J, SPJ, S
WHERE
    J.JNO = SPJ.JNO
    AND S.SNO = SPJ.SNO
    AND S.CITY = '上海';

-- 7

SELECT JNO
FROM SPJ
WHERE NOT EXISTS(
        SELECT *
        FROM SPJ, S, J
        WHERE
            SPJ.JNO = J.JNO
            AND SPJ.SNO = S.SNO
            AND S.CITY = '天津'
    );

-- 8

UPDATE P SET COLOR = '蓝色' WHERE COLOR = '红色';

-- 9

UPDATE SPJ SET SNO='S3' WHERE SNO='S5' AND PNO='P6' AND JNO='J4';

-- 10

DELETE FROM SPJ WHERE SNO='S2';

DELETE FROM S WHERE SNO='S2';

-- 11

INSERT INTO SPJ(SNO,JNO,PNO,QTY) VALUES('S2','J6','P4',200);

-- Ques9

-- 建立视图

CREATE VIEW SPJ_VIEW AS 
	SELECT SNO, PNO, QTY
	FROM SPJ
	WHERE JNO = (
	        SELECT JNO
	        FROM J
	        WHERE JNAME = '三建'
	    );
; 

-- (1)

SELECT PNO, QTY FROM SPJ_VIEW;

-- (2)

SELECT PNO QTY FROM SPJ WHERE SNO = 'S1';